###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "its a me, mario",
  "number": "40401-2432"
}

### number to string
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "waluiiiiiiigiiiiiii",
  "number": 404012432
}

### missing number entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "its a me, mario"
}

### missing name entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "40401-2432"
}

### missing entries
POST http://localhost:3001/api/persons
Content-Type: application/json

{
}

### missing entries
POST http://localhost:3001/api/persons
Content-Type: application/json

### wrong MIME
POST http://localhost:3001/api/persons
Content-Type: text/plain

{
  "name": "its a me, mario",
  "number": "40401-2432"
}

### wrong MIME -- json as string auto infered
POST http://localhost:3001/api/persons

"{\"name\": \"its a me, mario\",\"number\": \"40401-2432\"}"

###
GET http://localhost:3001/api/persons/1

### No id === 5
GET http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/1

### No id === 5
DELETE http://localhost:3001/api/persons/5
