POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "39-44-5323523"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dan Abramov",
  "number": "12-43-234345"
}
  
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mary Poppendieck",
  "number": "39-23-6423122"
}